rgw_setup skeleton (Mini-provisioner + directory structure
Seagate/cortx-rgw-integration pull request #11
Opened 2022-01-27 05:05 UTC by sachitanands

Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-01-28 09:07 UTC, cdeshmukh approved these changes

2022-01-28 09:10 UTC, shriya-deshmukh submitted a review, later dismissed

2022-01-31 07:01 UTC, rahul-tripathi-git requested changes
Kingly change the year of Copyright to 2022 from 2021 in all the files.

2022-01-31 07:03 UTC, cdeshmukh approved these changes

2022-01-31 09:12 UTC, shriya-deshmukh submitted a review, later dismissed

2022-01-31 09:20 UTC, sachitanands commented on src/setup/rgw.py
> +    """Represents Utils and Performs setup related actions."""
done

2022-01-31 09:21 UTC, shriya-deshmukh approved these changes

2022-01-31 09:28 UTC, rahul-tripathi-git approved these changes
+1

2022-01-31 09:30 UTC, cdeshmukh approved these changes

2022-01-31 10:26 UTC, merged